services:
  backend:
    image: sjc.vultrcr.com/secretsign/go
    build:
      context: .
      dockerfile: build/go.Dockerfile
    container_name: backend
    hostname: backend
    volumes:
      - ./:/backend/
      - .cache/backend/.vscode-server/:/root/.vscode-server/
      - .cache/backend/go/pkg/:/go/pkg/
    environment:
      GROQ_KEY: YOUR_GROQ_KEY
    ports:
      - 8000:8000
    stop_grace_period: 1s
    command: sleep 1000000
